steps:

- id: Build Image
  name: 'hashicorp/packer:latest'
  args: ["build",
        "-force",
        "-var","project_id=$PROJECT_ID",
        "-var","zone=$_ZONE",
        "-var","image_name=${_IMAGE_FAMILY}-${SHORT_SHA}",
        "-var","image_family=${_IMAGE_FAMILY}",
        "-var","subnet=${_SUBNETWORK}",
        "-var","zone=${_ZONE}",
        "img/packer.json"]

# Test the image #

substitutions:
    _ZONE: 'us-central1-c'
    _IMAGE_FAMILY: 'waterchange-rcc'
    _SUBNETWORK: 'default'
    _PACKER_JSON: 'img/packer.json'

timeout : 43200s
